name: MazeGen
version: 1.0
main: com.brandonjja.mazegen.MazeGen
author: Brandonjja
description: Maze Generation in Minecraft
commands:
    generate:
        usage: /generate
        description: Generates a maze in the selected region
    mazewand:
        usage: /mazewand
        description: Grants you the Maze Wand